worker_processes auto;

events {
    worker_connections 2048;
}

http {
    server {
        listen 8002;
        server_name localhost;

        root /var/www/html/x3microservices-lists-service/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass x3microservices-lists-service-php:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
    }
}
